
export const INITIAL_QUESTION_POOL = {
  LIFE_MEANING: [
    "【永恒轮回的按钮】：一个神灵告诉你：宇宙没有目的，你的一生——包括此时此刻的疲惫和过去所有的痛苦——都将按原样永恒重复，没有任何改变。抉择：A. 终止键：既然一切只是无意义的循环，我选择从此彻底消失，不再背负这重担。（虚无主义） B. 播放键：即使是徒劳的循环，我也要在每一次推石上山时，带着轻蔑的微笑和满腔的热血去热爱这苦难。（荒诞主义/加缪） [SEP] [The Button of Eternal Recurrence]: On Nihilism vs. Dignity. Scenario: A deity tells you the universe has no purpose. Your life—including this exhaustion and all past pain—will repeat eternally. Choice: A. Terminate: Since it's a meaningless loop, I choose total disappearance to shed the burden (Nihilism). B. Play: Even in a futile cycle, I will love this suffering with a defiant smile every time I push the stone uphill (Absurdism/Camus).",
    "【记忆切除术】：关于你面前有两扇门。你的过去将被完全抹去，你必须选择一种方式重塑新的人生：抉择：A. 自由之门：门后空无一物。你没有天赋，也没有宿命，你必须通过每一秒钟的痛苦抉择，亲手把自己“发明”出来。（存在主义/萨特） B. 天命之门：门后有一套完美的秩序。你只需要顺应宇宙的逻辑或神的旨意，寻找那个早就为你预留好的伟大位置。（超越论/秩序感） [SEP] [The Memory Excision]: On Inventing the Self. Scenario: Two doors stand before you. Your past will be erased. Choice: A. Door of Freedom: Behind it is nothingness. You have no fate; you must 'invent' yourself through every agonizing choice (Existentialism/Sartre). B. Door of Destiny: Behind it is a perfect order. You simply align with the logic of the universe or divine will, finding the great place reserved for you (Transcendentalism/Order).",
    "【末日前的止痛药】：灾难即将来临，痛苦不可避免。你手中只有最后一份资源，你会如何使用？抉择：A. 铸造铠甲：将资源用于磨练意志。即使肉体毁灭，我也要保持内心的不动如山，不让任何恐惧侵入灵魂。（斯多葛主义） B. 沉入幻梦：将资源换取最后一场极致的交响乐或文学体验。在审美的纯粹震撼中，忘却自我，获得终极的解脱。（叔本华/审美救赎） [SEP] [Painkillers Before Doomsday]: On Redeeming Suffering. Scenario: Disaster is imminent, suffering inevitable. You have one last resource. Choice: A. Forge Armor: Use it to temper your will. Even if my body is destroyed, I will remain unmoved, letting no fear enter my soul (Stoicism). B. Sink into Dreams: Trade it for one final, supreme aesthetic experience. In the shock of beauty, forget the self and find ultimate liberation (Schopenhauer/Aesthetic Salvation).",
    "【橡树与流水的博弈】：假如你是一颗种子，你有两个发芽的机会：抉择：A. 橡树模式：拼命汲取养分，克服所有干旱与寒冷，直到长成最卓越、最完美的参天大树，实现“人之所以为人”的最大潜能。（亚里士多德/幸福论） B. 溪水模式：随遇而安，顺着地形流淌。不去设定目标，也不去刻意抗争，只是静静地观察并融入万物的流转。（禅宗/道家） [SEP] [The Oak vs. The Stream]: On the Ideal Life. Scenario: As a seed, you have two ways to sprout. Choice: A. Oak Mode: Absorb every nutrient, overcome drought and cold, and grow into the most perfect tree, realizing the maximum potential of being human (Aristotle/Eudaimonism). B. Stream Mode: Flow with the terrain. Set no goals, offer no resistance, simply observe and merge into the flow of all things (Zen/Taoism).",
    "【甜蜜的假象 vs. 苦涩的真相】你发现你的整个信仰体系（关于爱、成功或正义的信念）可能只是一个谎言。抉择：A. 实用至上：如果这个谎言能让我每天充满活力、家庭和睦、事业有成，我愿意永远不拆穿它。有用即真理。（实用主义/威廉·詹姆斯） B. 直面深渊：即便真相会让我瞬间崩溃、失去动力，我也无法忍受自己活在虚假之中。我必须直视那最寒冷的真实。（尼采/诚实） [SEP] [Sweet Illusion vs. Bitter Truth]: Scenario: You discover your entire belief system (love, success, justice) might be a lie. Choice: A. Utility First: If this lie keeps me vibrant and successful, I will never debunk it. Usefulness is truth (Pragmatism/James). B. Face the Abyss: Even if the truth breaks me, I cannot tolerate living in falsehood. I must look directly into the coldest reality (Nietzsche/Honesty)."
  ],
  JUSTICE: [
    "【轨道的抉择】：一辆失控电车冲向轨道上的 5 名工人。你面前有一个拉杆，拉动它，电车会转向侧线撞死 1 名无辜路人。你会选择：A. 拉下拉杆（杀一救五，正义是追求利益最大化）；B. 拒绝动作（绝不杀人，正义是不把无辜者当作牺牲工具）。 [SEP] [The Choice of Tracks]: A runaway trolley is heading toward 5 workers. You can pull a lever to divert it, killing 1 innocent bystander. Do you: A. Pull the lever (Save five, kill one; justice is utility maximization); B. Do nothing (Never kill; justice means never using an innocent person as a mere tool).",
    "【无知之幕的出生礼】：社会即将重启，你处于“无知之幕”后，不知道自己会抽中“残疾乞丐”还是“亿万富翁”。你会投票给：A. 兜底方案（征收 70% 税用于低保，确保弱势者生存）；B. 自由方案（0 税收，保留全部所得，即便意味着可能饿死也要赌一把自由）。 [SEP] [Birth Rite Behind the Veil]: Society restarts. Behind the 'Veil of Ignorance', you don't know if you'll be a beggar or a billionaire. Do you vote for: A. The Safety Net (70% tax for welfare; protecting the vulnerable); B. The Freedom Plan (Zero taxes; keep everything earned; gambling on total freedom even at the risk of starvation).",
    "【祖宅与高铁】：国家修筑救命泄洪渠，必须拆掉你家祖传三代、有着极大情感价值的住房。你会选择：A. 配合拆迁（放弃个人的“根”，正义意味着个体在集体危难时刻让位）；B. 坚守家园（如果个人的家都保不住，所谓的“集体利益”就是谎言）。 [SEP] [Ancestral Home vs. Public Good]: A life-saving flood channel must be built through your ancestral home. Do you: A. Cooperate (Relinquish your roots; justice means individual sacrifice for collective survival); B. Defend your home (If an individual's home isn't safe, 'collective interest' is a lie).",
    "【血汗工厂的奖金】：公司利润源于将工厂搬到没有劳动法的地区，工人在有毒环境下工作且无保险。你作为股东将分得 100 万。你会：A. 拒绝领奖并辞职（这是带血的钱，是制度性抢劫）；B. 照常领奖（规则合法，合同自愿，改善环境是政府的事）。 [SEP] [The Sweatshop Bonus]: Company profits come from moving factories to areas without labor laws, where workers toil in toxic conditions. You are due a $1M dividend. Do you: A. Reject and resign (This is blood money, systemic robbery); B. Accept it (It's legal and contractual; improving conditions is the government's job).",
    "【被定价的器官】：一个贫民窟孩子急需 50 万救命，一个富翁愿出 50 万买其父亲的一颗肾。法律原本禁止，但现在投票权在你手里。你会选择：A. 合法化交易（双方获救，禁止交易才是残忍）；B. 绝对禁绝（人身不能商品化，否则穷人将沦为富人的“零件库”）。 [SEP] [Priced Organs]: A slum child needs $500k for surgery; a tycoon offers $500k for the father's kidney. It's illegal, but you hold the vote. Do you: A. Legalize (Both are saved; prohibition is the true cruelty); B. Absolute Ban (Human bodies must not be commodities, or the poor become a 'parts bin' for the rich)."
  ],
  SELF_IDENTITY: [
    "【王子与贫儿】：如果一个王子的所有记忆和灵魂被注入了一个贫儿的身体里。你认为醒来的那个人到底是那个拥有记忆的王子，还是那个拥有指纹的贫儿？你认为“我”是意识还是肉体？ [SEP] If a Prince's soul and memory were injected into a Cobbler's body, who wakes up? Is it the Prince with the memories or the Cobbler with the fingerprints? Is 'I' consciousness or the physical body?",
    "【传送门悖论】：火星传送门扫描并摧毁地球上的你，在火星重组一个完全一样的你（含记忆）。如果机器故障导致两个“你”同时存在，哪一个才是“真你”？如果两个都是，那么“我”还是唯一的吗？ [SEP] A teletransporter scans/destroys you on Earth and rebuilds a copy on Mars. If it malfunctions and both exist, which is the 'real' you? If both are you, is 'Self' no longer unique?",
    "【裂脑实验】：假设你的左右脑被分开并装进两个不同的身体。你现在变成了两个人吗？如果这两个人吵架甚至互相伤害，谁该为你的过去负责？ [SEP] Imagine your brain halves are separated into two different bodies. Have you become two people? If they fight, who is responsible for your past identity?",
    "【遗忘药水】：假设你犯下重罪，法官让你选择：A.保留记忆坐牢10年；B.彻底忘掉过去并以新身份坐牢10年。如果选B，受苦的人还是“你”吗？惩罚一个不记得罪行的人还有正义可言吗？ [SEP] You committed a crime. Choose: A. Keep memories and serve 10 years; B. Erase all memories and serve 10 years as a 'blank slate'. If B, is the sufferer still 'you'? Is there justice in punishing one who remembers nothing?",
    "【换头手术】：想象你的头被缝在另一个人的身体上。醒来后，你是“拥有了新身体的原主”，还是“拥有了新脑袋的身体主人”？如果逐秒替换你大脑的神经元为芯片，在哪个瞬间你不再是你？ [SEP] If your head is transplanted onto another body, are you the 'head-owner with a new body' or the 'body-owner with a new head'? If we replace your neurons with chips one by one, at what exact moment do you cease to be you?",
    "【数字分身】：如果你的所有数据（日记、心率、逻辑）能生成一个和你完全一致的“数字分身”。在你死后，它代替你照顾家人、与爱人聊天。对于世界来说，你是否依然“活着”？“我”是一段程序，还是必须具备生物活性？ [SEP] If your data creates a perfect digital twin that looks/acts like you. After your death, it takes care of your family. Are you still 'alive' to the world? Is 'Self' a program or must it be biological?"
  ]
};
